
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileServerWS", targetNamespace = "http://soap.srv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileServerWS {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "run", targetNamespace = "http://soap.srv/", className = "ws.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://soap.srv/", className = "ws.RunResponse")
    @Action(input = "http://soap.srv/FileServerWS/runRequest", output = "http://soap.srv/FileServerWS/runResponse")
    public void run();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mkdir", targetNamespace = "http://soap.srv/", className = "ws.Mkdir")
    @ResponseWrapper(localName = "mkdirResponse", targetNamespace = "http://soap.srv/", className = "ws.MkdirResponse")
    @Action(input = "http://soap.srv/FileServerWS/mkdirRequest", output = "http://soap.srv/FileServerWS/mkdirResponse")
    public boolean mkdir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cp", targetNamespace = "http://soap.srv/", className = "ws.Cp")
    @ResponseWrapper(localName = "cpResponse", targetNamespace = "http://soap.srv/", className = "ws.CpResponse")
    @Action(input = "http://soap.srv/FileServerWS/cpRequest", output = "http://soap.srv/FileServerWS/cpResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.srv/FileServerWS/cp/Fault/IOException")
    })
    public boolean cp(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rmdir", targetNamespace = "http://soap.srv/", className = "ws.Rmdir")
    @ResponseWrapper(localName = "rmdirResponse", targetNamespace = "http://soap.srv/", className = "ws.RmdirResponse")
    @Action(input = "http://soap.srv/FileServerWS/rmdirRequest", output = "http://soap.srv/FileServerWS/rmdirResponse")
    public boolean rmdir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rmfile", targetNamespace = "http://soap.srv/", className = "ws.Rmfile")
    @ResponseWrapper(localName = "rmfileResponse", targetNamespace = "http://soap.srv/", className = "ws.RmfileResponse")
    @Action(input = "http://soap.srv/FileServerWS/rmfileRequest", output = "http://soap.srv/FileServerWS/rmfileResponse")
    public boolean rmfile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.FileInfo
     * @throws InfoNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileInfo", targetNamespace = "http://soap.srv/", className = "ws.GetFileInfo")
    @ResponseWrapper(localName = "getFileInfoResponse", targetNamespace = "http://soap.srv/", className = "ws.GetFileInfoResponse")
    @Action(input = "http://soap.srv/FileServerWS/getFileInfoRequest", output = "http://soap.srv/FileServerWS/getFileInfoResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://soap.srv/FileServerWS/getFileInfo/Fault/InfoNotFoundException")
    })
    public FileInfo getFileInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws InfoNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.FileContent
     * @throws InfoNotFoundException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileContent", targetNamespace = "http://soap.srv/", className = "ws.GetFileContent")
    @ResponseWrapper(localName = "getFileContentResponse", targetNamespace = "http://soap.srv/", className = "ws.GetFileContentResponse")
    @Action(input = "http://soap.srv/FileServerWS/getFileContentRequest", output = "http://soap.srv/FileServerWS/getFileContentResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://soap.srv/FileServerWS/getFileContent/Fault/InfoNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://soap.srv/FileServerWS/getFileContent/Fault/IOException")
    })
    public FileContent getFileContent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception, InfoNotFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws InfoNotFoundException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createFile", targetNamespace = "http://soap.srv/", className = "ws.CreateFile")
    @ResponseWrapper(localName = "createFileResponse", targetNamespace = "http://soap.srv/", className = "ws.CreateFileResponse")
    @Action(input = "http://soap.srv/FileServerWS/createFileRequest", output = "http://soap.srv/FileServerWS/createFileResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://soap.srv/FileServerWS/createFile/Fault/InfoNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://soap.srv/FileServerWS/createFile/Fault/IOException")
    })
    public boolean createFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        FileContent arg1)
        throws IOException_Exception, InfoNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws InfoNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dir", targetNamespace = "http://soap.srv/", className = "ws.Dir")
    @ResponseWrapper(localName = "dirResponse", targetNamespace = "http://soap.srv/", className = "ws.DirResponse")
    @Action(input = "http://soap.srv/FileServerWS/dirRequest", output = "http://soap.srv/FileServerWS/dirResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://soap.srv/FileServerWS/dir/Fault/InfoNotFoundException")
    })
    public List<String> dir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws InfoNotFoundException_Exception
    ;

}
